/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ConfigController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["UsersController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["UsersController_updateMe"];
        trace?: never;
    };
    "/me/become-pro": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["UsersController_becomePro"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CategoriesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProvidersController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProvidersController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProvidersController_slots_"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search/ai": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProvidersController_searchAi"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/checkout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_checkout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/mock/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_mockComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/p24/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_p24Webhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/paypal/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PaymentsController_paypalWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PaymentsController_getOne"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["BookingsController_list"];
        put?: never;
        post: operations["BookingsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/accept-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_acceptQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/decline-quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_declineQuote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_review"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bookings/{id}/approve-completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["BookingsController_approveCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["FavoritesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/favorites/{providerProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["FavoritesController_add"];
        delete: operations["FavoritesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_apply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProviderAreaController_dashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProviderAreaController_requests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/requests/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_decline"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/requests/{id}/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_quote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/requests/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_complete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProviderAreaController_calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ProviderAreaController_createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["ProviderAreaController_deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProviderAreaController_billing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/provider/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProviderAreaController_payouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_feed"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_blockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_unblockUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_verifyProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_rejectProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_bookings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_cancelBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/bookings/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_completeBooking"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/calendar/{providerProfileId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_calendar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/blocks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_createBlock"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/blocks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["AdminController_deleteBlock"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_categories"];
        put?: never;
        post: operations["AdminController_createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/categories/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["AdminController_updateCategory"];
        trace?: never;
    };
    "/admin/billing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_billing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_adminPayments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AdminController_adminPayouts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payouts/run-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_runPayoutBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/payments/auto-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AdminController_autoApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/auto-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CronController_autoApprove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cron/payouts/run-batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["CronController_runPayoutBatch"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BrandConfigResponseEntity: {
            currency: string;
            supportedLocales: string[];
            taxRatePrivate: number;
            paymentMethods: ("P24_BLIK" | "PAYPAL")[];
        };
        RequestCodeDto: {
            /** Format: email */
            email: string;
        };
        RequestCodeResponseEntity: {
            ok: boolean;
            /** @description Only present outside MAIL_ALLOWLIST / in dev (demo login) */
            devCode?: string;
        };
        VerifyDto: {
            /** Format: email */
            email: string;
            /**
             * @description 8-digit OTP code
             * @example 12345678
             */
            code: string;
        };
        SavedAddressEntity: {
            label: string;
            addr: string;
        };
        MeEntity: {
            id: number;
            email: string;
            name: string;
            isCustomer: boolean;
            isProvider: boolean;
            isAdmin: boolean;
            locationLabel?: string | null;
            lat?: number | null;
            lng?: number | null;
            savedAddresses?: components["schemas"]["SavedAddressEntity"][] | null;
            providerProfileId?: number | null;
            providerStatus?: string | null;
            isPro: boolean;
            proTermsAcceptedAt?: string | null;
            emailNotifications: boolean;
        };
        VerifyResponseEntity: {
            accessToken: string;
            user: components["schemas"]["MeEntity"];
        };
        SavedAddressDto: {
            label?: string;
            addr?: string;
        };
        UpdateMeDto: {
            name?: string;
            locationLabel?: string;
            lat?: number;
            lng?: number;
            savedAddresses?: components["schemas"]["SavedAddressDto"][];
            emailNotifications?: boolean;
        };
        CategoryEntity: {
            id: number;
            name: string;
            slug: string;
            active: boolean;
            providerCount?: number;
            count?: number;
        };
        ProviderListItemEntity: {
            id: number;
            userId: number;
            name: string;
            init: string;
            categorySlug: string;
            categoryName: string;
            rating: number;
            reviewCount: number;
            priceFromLabel: string;
            distanceKm: number;
            lat: number;
            lng: number;
            nextSlotLabel: string;
            verified: boolean;
            featured: boolean;
            locLine: string;
            spotAddress?: string | null;
            /** @enum {string} */
            businessType: "PRIVATE" | "JDG";
        };
        ServiceEntity: {
            id: number;
            providerProfileId?: number;
            title: string;
            durationLabel: string;
            /** @enum {string} */
            priceType: "FIXED" | "HOURLY" | "QUOTE";
            priceLabel: string;
            /** @description grosze (int) */
            priceAmount?: number | null;
            /** @enum {string} */
            location: "CLIENT" | "SPOT";
            sort?: number;
        };
        ProviderReviewEntity: {
            id: number;
            rating: number;
            text: string;
            createdAt?: string;
            customerName?: string;
            authorName?: string;
            name?: string;
        };
        ProviderDetailEntity: {
            id: number;
            userId: number;
            name: string;
            init: string;
            categorySlug: string;
            categoryName: string;
            rating: number;
            reviewCount: number;
            priceFromLabel: string;
            distanceKm: number;
            lat: number;
            lng: number;
            nextSlotLabel: string;
            verified: boolean;
            featured: boolean;
            locLine: string;
            spotAddress?: string | null;
            /** @enum {string} */
            businessType: "PRIVATE" | "JDG";
            bio: string;
            travelRadiusKm?: number;
            responseMinutes?: number;
            docsNote?: string;
            /** @description weekday -> [openHour, closeHour] tuple */
            workHours?: {
                [key: string]: number[];
            } | null;
            services: components["schemas"]["ServiceEntity"][];
            reviews: components["schemas"]["ProviderReviewEntity"][];
        };
        SlotEntity: {
            label: string;
            available: boolean;
        };
        SlotsResponseEntity: {
            times: components["schemas"]["SlotEntity"][];
        };
        SearchAiDto: {
            query: string;
        };
        AiSearchMatchEntity: {
            id: number;
            userId: number;
            name: string;
            init: string;
            categorySlug: string;
            categoryName: string;
            rating: number;
            reviewCount: number;
            priceFromLabel: string;
            distanceKm: number;
            lat: number;
            lng: number;
            nextSlotLabel: string;
            verified: boolean;
            featured: boolean;
            locLine: string;
            spotAddress?: string | null;
            /** @enum {string} */
            businessType: "PRIVATE" | "JDG";
            why: string;
        };
        AiSearchResponseEntity: {
            response: string;
            matches: components["schemas"]["AiSearchMatchEntity"][];
        };
        CheckoutDto: {
            bookingId: number;
            /** @enum {string} */
            method: "P24_BLIK" | "PAYPAL";
        };
        CheckoutResponseEntity: {
            paymentId: number;
            redirectUrl?: string | null;
        };
        MockCompleteDto: {
            paymentId: number;
        };
        PaymentEntity: {
            id: number;
            bookingId: number;
            /** @enum {string} */
            method: "P24_BLIK" | "PAYPAL";
            /** @enum {string} */
            status: "PENDING" | "HELD" | "CAPTURED" | "RELEASED" | "REFUNDED" | "FAILED";
            /** @description grosze (int) */
            amount: number;
            currency: string;
            externalId?: string | null;
            redirectUrl?: string | null;
            heldAt?: string | null;
            capturedAt?: string | null;
            releasedAt?: string | null;
            refundedAt?: string | null;
            createdAt: string;
        };
        CreateBookingDto: {
            providerProfileId: number;
            serviceId: number;
            /** Format: date-time */
            startAt?: string;
            preferredWindow?: string;
            notes?: string;
            address?: string;
            atSpot: boolean;
        };
        BookingProviderSummary: {
            id: number;
            name: string;
            init?: string;
            spotAddress?: string | null;
        };
        BookingServiceSummary: {
            id: number;
            title: string;
            priceLabel?: string;
        };
        BookingReviewSummary: {
            id: number;
            rating: number;
        };
        BookingEntity: {
            id: number;
            displayId?: string;
            /** @enum {string} */
            type: "INSTANT" | "QUOTE";
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "AWAITING_APPROVAL" | "COMPLETED" | "CANCELLED" | "DECLINED";
            statusLabel?: string;
            /** @enum {string|null} */
            quoteStatus?: "AWAITING" | "QUOTED" | "ACCEPTED" | null;
            /** @description grosze (int) */
            quotedAmount?: number | null;
            startAt?: string | null;
            endAt?: string | null;
            preferredWindow?: string | null;
            atSpot: boolean;
            address: string;
            notes?: string | null;
            priceLabel: string;
            createdAt: string;
            customerId?: number;
            providerProfileId: number;
            serviceId: number;
            acknowledged?: boolean;
            providerName?: string;
            providerInit?: string;
            serviceTitle?: string;
            customerName?: string;
            hasReview?: boolean;
            provider?: components["schemas"]["BookingProviderSummary"] | null;
            service?: components["schemas"]["BookingServiceSummary"] | null;
            review?: components["schemas"]["BookingReviewSummary"] | null;
            paymentRequired?: boolean;
            payment?: components["schemas"]["PaymentEntity"] | null;
            canCancel?: boolean;
            canApprove?: boolean;
            canReview?: boolean;
            awaitingApprovalAt?: string | null;
        };
        BookingsSplitEntity: {
            upcoming: components["schemas"]["BookingEntity"][];
            completed: components["schemas"]["BookingEntity"][];
        };
        ReviewDto: {
            /** @enum {number} */
            rating: 1 | 2 | 3 | 4 | 5;
            text: string;
        };
        ApplyProviderDto: {
            categoryId: number;
            bio: string;
            /** @enum {string} */
            businessType: "PRIVATE" | "JDG";
            travelRadiusKm?: number;
            spotAddress?: string;
        };
        QuoteDto: {
            /**
             * @description Amount in grosze (e.g. 35000 = 350 zł)
             * @example 35000
             */
            amount: number;
        };
        CreateBlockDto: {
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        PayoutEntity: {
            id: number;
            providerProfileId?: number;
            paymentId: number;
            bookingId?: number;
            /** @description grosze (int) */
            grossAmount: number;
            /** @description grosze (int) */
            taxAmount: number;
            /** @description grosze (int) */
            netAmount: number;
            /** @enum {string} */
            status: "PENDING" | "PAID";
            statusLabel?: string;
            batchDate?: string | null;
            createdAt: string;
        };
        AdminStatsEntity: {
            users: number;
            usersWeekDelta: number;
            providers: number;
            pendingProviders: number;
            bookingsToday: number;
            cancelledToday: number;
            revenueMonthLabel: string;
            taxMonthLabel: string;
        };
        EventLogItemEntity: {
            text: string;
            /** @description dot color hex */
            dot: string;
            /** @description pre-formatted relative time, e.g. "3 min temu" */
            time: string;
        };
        AdminUserEntity: {
            id: number;
            name: string;
            email: string;
            blocked: boolean;
            roles?: string;
            isCustomer?: boolean;
            isProvider?: boolean;
            isAdmin?: boolean;
            bookingsCount?: number;
            bookingCount?: number;
            count?: number;
        };
        AdminProviderCategorySummary: {
            name: string;
        };
        AdminProviderEntity: {
            id: number;
            userId?: number;
            name: string;
            init?: string;
            categoryName?: string;
            category?: components["schemas"]["AdminProviderCategorySummary"] | null;
            /** @enum {string} */
            businessType: "PRIVATE" | "JDG";
            /** @enum {string} */
            status: "PENDING" | "VERIFIED" | "REJECTED";
            docsNote?: string;
            rating?: number;
            reviewCount?: number;
        };
        AdminBookingRowEntity: {
            id: number;
            /** @description customer display name */
            customer: string;
            /** @description provider display name */
            provider: string;
            /** @description service title */
            service: string;
            /** @description pre-formatted schedule label, e.g. "wt 21.07 9:00" or "do ustalenia" */
            when: string;
            /** @description pre-formatted price label, e.g. "120 zł" */
            price: string;
            /** @enum {string} */
            status: "PENDING" | "CONFIRMED" | "AWAITING_APPROVAL" | "COMPLETED" | "CANCELLED" | "DECLINED";
            /** @description pre-formatted status label (PL) */
            statusLabel: string;
            canCancel: boolean;
        };
        AdminCalendarCellEntity: {
            /** @enum {string} */
            status: "booked" | "blocked" | "free" | "off";
            label?: string | null;
            blockId?: number | null;
        };
        AdminCalendarRowEntity: {
            hour?: number;
            label?: string;
            cells: components["schemas"]["AdminCalendarCellEntity"][];
        };
        AdminCalendarResponseEntity: {
            weekStart?: string;
            days?: string[];
            rows?: components["schemas"]["AdminCalendarRowEntity"][];
            grid?: components["schemas"]["AdminCalendarRowEntity"][];
        };
        AdminCreateBlockDto: {
            providerProfileId: number;
            /** Format: date-time */
            startAt: string;
            /** Format: date-time */
            endAt: string;
        };
        TimeBlockEntity: {
            id: number;
            providerProfileId: number;
            startAt: string;
            endAt: string;
        };
        CreateCategoryDto: {
            /** @example Elektryk */
            name: string;
        };
        UpdateCategoryDto: {
            active: boolean;
        };
        AdminDocumentEntity: {
            number: string;
            /** @description provider display name (canonical field — always present) */
            who: string;
            /** @description alias of `who` */
            providerName?: string;
            provider?: Record<string, never> | null;
            type: string;
            status: string;
            amount: string;
            tax: string;
        };
        AdminBillingEntity: {
            docsCount: number;
            taxTotalLabel: string;
            payoutTotalLabel: string;
            nextPayoutLabel: string;
            privatePersonsCount?: number;
            documents: components["schemas"]["AdminDocumentEntity"][];
        };
        AdminPaymentRowEntity: {
            id: number;
            bookingId: number;
            /** @enum {string} */
            method: "P24_BLIK" | "PAYPAL";
            methodLabel: string;
            /** @enum {string} */
            status: "PENDING" | "HELD" | "CAPTURED" | "RELEASED" | "REFUNDED" | "FAILED";
            statusLabel: string;
            /** @description grosze (int) */
            amount: number;
            /** @description pre-formatted, e.g. "120 zł" */
            amountLabel?: string;
            currency: string;
            /** @description customer display name */
            customerName: string;
            /** @description provider display name */
            providerName: string;
            customer?: Record<string, never> | null;
            provider?: Record<string, never> | null;
            externalId?: string | null;
            redirectUrl?: string | null;
            heldAt?: string | null;
            capturedAt?: string | null;
            releasedAt?: string | null;
            refundedAt?: string | null;
            createdAt: string;
        };
        AdminPayoutRowEntity: {
            id: number;
            /** @description provider display name */
            providerName: string;
            provider?: Record<string, never> | null;
            bookingId: number;
            /** @description grosze (int) */
            grossAmount: number;
            /** @description pre-formatted, e.g. "120 zł" */
            grossAmountLabel?: string;
            /** @description grosze (int) */
            taxAmount: number;
            /** @description pre-formatted, e.g. "120 zł" */
            taxAmountLabel?: string;
            /** @description grosze (int) */
            netAmount: number;
            /** @description pre-formatted, e.g. "120 zł" */
            netAmountLabel?: string;
            /** @enum {string} */
            status: "PENDING" | "PAID";
            statusLabel: string;
            batchDate?: string | null;
            createdAt: string;
        };
        RunPayoutBatchResponseEntity: {
            batched?: number;
            count?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    ConfigController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandConfigResponseEntity"];
                };
            };
        };
    };
    AuthController_requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResponseEntity"];
                };
            };
        };
    };
    AuthController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyResponseEntity"];
                };
            };
        };
    };
    UsersController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeEntity"];
                };
            };
        };
    };
    UsersController_updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeEntity"];
                };
            };
        };
    };
    UsersController_becomePro: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeEntity"];
                };
            };
        };
    };
    CategoriesController_list: {
        parameters: {
            query: {
                all: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"][];
                };
            };
        };
    };
    ProvidersController_list: {
        parameters: {
            query: {
                category: string;
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListItemEntity"][];
                };
            };
        };
    };
    ProvidersController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderDetailEntity"];
                };
            };
        };
    };
    ProvidersController_slots_: {
        parameters: {
            query: {
                day: string;
                serviceId: string;
            };
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SlotsResponseEntity"];
                };
            };
        };
    };
    ProvidersController_searchAi: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchAiDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiSearchResponseEntity"];
                };
            };
        };
    };
    PaymentsController_checkout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckoutResponseEntity"];
                };
            };
        };
    };
    PaymentsController_mockComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MockCompleteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEntity"];
                };
            };
        };
    };
    PaymentsController_p24Webhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_paypalWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    PaymentsController_getOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentEntity"];
                };
            };
        };
    };
    BookingsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingsSplitEntity"];
                };
            };
        };
    };
    BookingsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBookingDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_cancel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_acceptQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_declineQuote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_review: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    BookingsController_approveCompletion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    FavoritesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListItemEntity"][];
                };
            };
        };
    };
    FavoritesController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerProfileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    FavoritesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                providerProfileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_apply: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyProviderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_dashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_requests: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_decline: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_quote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuoteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_complete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_calendar: {
        parameters: {
            query: {
                day: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBlockDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_billing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    ProviderAreaController_payouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PayoutEntity"][];
                };
            };
        };
    };
    AdminController_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsEntity"];
                };
            };
        };
    };
    AdminController_feed: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventLogItemEntity"][];
                };
            };
        };
    };
    AdminController_users: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserEntity"][];
                };
            };
        };
    };
    AdminController_blockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_unblockUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_providers: {
        parameters: {
            query: {
                status: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminProviderEntity"][];
                };
            };
        };
    };
    AdminController_verifyProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_rejectProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_bookings: {
        parameters: {
            query: {
                status: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBookingRowEntity"][];
                };
            };
        };
    };
    AdminController_cancelBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    AdminController_completeBooking: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookingEntity"];
                };
            };
        };
    };
    AdminController_calendar: {
        parameters: {
            query: {
                weekStart: string;
            };
            header?: never;
            path: {
                providerProfileId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminCalendarResponseEntity"];
                };
            };
        };
    };
    AdminController_createBlock: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateBlockDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeBlockEntity"];
                };
            };
        };
    };
    AdminController_deleteBlock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AdminController_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"][];
                };
            };
        };
    };
    AdminController_createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"];
                };
            };
        };
    };
    AdminController_updateCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCategoryDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryEntity"];
                };
            };
        };
    };
    AdminController_billing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminBillingEntity"];
                };
            };
        };
    };
    AdminController_adminPayments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPaymentRowEntity"][];
                };
            };
        };
    };
    AdminController_adminPayouts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminPayoutRowEntity"][];
                };
            };
        };
    };
    AdminController_runPayoutBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunPayoutBatchResponseEntity"];
                };
            };
        };
    };
    AdminController_autoApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CronController_autoApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CronController_runPayoutBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
